apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qjcp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-qjcp@sha256:48b5a2e009e52e533c9e228db31e4f2dd4853f0a21d0024008ca65ca28dfe72c
        name: my-nodejs
        resources: {}
status: {}
